CLASS zbp_acb_r_mass_change DEFINITION
  PUBLIC ABSTRACT FINAL
  FOR BEHAVIOR OF zacb_r_masschange.

  PUBLIC SECTION.

  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.


CLASS zbp_acb_r_mass_change IMPLEMENTATION.
ENDCLASS.
